
[tasks.rust_unit_test]
run_task = { name = ["rust_lib_unit_test", "shared_lib_unit_test"] }

[tasks.rust_lib_unit_test]
description = "Run rust-lib unit tests"
script = '''
cd rust-lib
RUST_LOG=info cargo test --no-default-features --features="sync"
'''

[tasks.shared_lib_unit_test]
description = "Run shared-lib unit test"
script = '''
cd ../shared-lib
RUST_LOG=info cargo test --no-default-features
'''

