#[build]
#target-dir = "./bin"

[target.x86_64-apple-darwin]
rustflags=["-C", "link-arg=-mmacosx-version-min=10.11"]

[target.aarch64-apple-darwin]
rustflags=["-C", "link-arg=-mmacosx-version-min=10.11"]